### ISSUE TITLE
Storing function references

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/function-references#1]
What are the options for actually storing a function reference in memory?
Local variables, heap memory etc.

**Comment by titzer** [comment]
I think `funcref`s can go anywhere `anyref`s can; i.e. globals, locals, tables, arguments, returns, but not into the Wasm memory.

**Comment by fgmccabe** [comment]
Which is, of course, the most interesting case for function closures...

**Comment by rossberg** [comment]
By virtue of being an additional form of reference type, they can be stored/passed like any other value of reference type, i.e., in locals, globals, parameters, results, tables, as @tizer said.

**Comment by rossberg** [comment]
This has been answered.
