### ISSUE TITLE
`Illegal macro parameter reference` in the spec

### ISSUE THREAD

**Issue by zapashcanon** [WebAssembly/function-references#101]
Hi @rossberg,

[Here](https://webassembly.github.io/function-references/core/syntax/types.html#instruction-types) the generation of the spec seems to be broken.

Screenshot:

![20230730_16h03m48s_sun](https://github.com/WebAssembly/function-references/assets/16472988/8c139040-768c-4b80-9ab1-0f508cfb5730)

**Comment by rossberg** [comment]
Hm, this works fine in the PDF. It seems to be a bug in MathJax, which somehow mishandles `\def` with parameter when an href appears in the expansion.

Unfortunately, I could not find any workaround other than removing the clickable xref for the arrow symbol, see #105.
