### ISSUE TITLE
call_ref $t: invalid value type 0x00

### ISSUE THREAD

**Issue by dy** [WebAssembly/function-references#119]
I am trying to add func refs support in [watr](https://github.com/dy/watr) and having some misunderstanding.

Take example from testsuite:

```
(module
  (type $t (func (result i32)))

  (func $nn (param $r (ref $t)) (result i32)
    (call_ref $t
      (block $l (result (ref $t))
        (br_on_non_null $l (local.get $r))
        (return (i32.const -1))
      )
    )
  )
)
````
[Wabt](https://webassembly.github.io/wabt/demo/wat2wasm/) fails to compile it:
```
Error: parseWat failed:
test.wast:5:15: error: unexpected token $t, expected ).
    (call_ref $t
              ^^
test.wast:7:9: error: unexpected token (, expected ).
        (br_on_non_null $l (local.get $r))
        ^
test.wast:7:10: error: unexpected token br_on_non_null.
        (br_on_non_null $l (local.get $r))
         ^^^^^^^^^^^^^^
test.wast:8:9: error: unexpected token (, expected ).
        (return (i32.const -1))
        ^
```

What else can I use to compile func refs? [spec wasm interpreter](https://github.com/WebAssembly/spec/tree/main/interpreter) doesn't compile on MacOS into vague reason
```
make                
rm -f wasm
dune build wasm.exe
File "dune", line 9, characters 15-19:  
9 |   (public_name wasm)
                   ^^^^
ld: library 'pthread' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
```

**Comment by dy** [comment]
Also if I do basic wasm2wat of [function references detector](https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/main/src/detectors/typed-function-references/index.js), it gives:
```
wasm2wat --enable-all func-refs.wasm                            
0000013: error: expected valid param type (got -0x1c)
```
As if it doesn't enable function-references.

**Comment by dy** [comment]
Ok, issue belongs to wabt repository.

**Comment by rossberg** [comment]
I do all my dev on MacOS, so the reference interpreter ought to compile and run fine. Pthreads is a standard OS library, if the linker doesn't find it on your system, then something seems wrong, perhaps with your PATH settings.
