### ISSUE TITLE
Tables with non-null element type

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/function-references#26]
Currently, table types require a defaultable (nullable) element type, in order to be able initialise a table.

We should probably lift that restriction and extend table definitions with an explicit initialisation value in form of a constant expression, which is optional but required for non-defaultable element types.

**Comment by binji** [comment]
As an alternative, we could use element segments for this. This could be a small win for users that have non-uniform initial value for their table, which I imagine is common. Though as you've mentioned, this could get a bit messy, since we'd need to require that the segment fully initializes the table.

For now, it's probably simpler to go with a single constant expression (like you've described) and use `table.init` afterward.

**Comment by manoskouk** [comment]
To revive this, I suggest the following binary format:

`tabletype ::= et:reftype flag limits init:expr?`

`flag in {0,1,2,3}`, if `et = (ref null t)`
`flag in {2,3}`, if `et = (ref t)`

`limits ::= u32`, if `flag in {0,2}`
`limits ::= u32 u32`, if `flag in {1,3}`

`init: ε`, if `flag in {0,1}`
`init:expr`, if `flag in {2,3}` with `expr:t` and `t <: et`

**Comment by rossberg** [comment]
@manoskouk, keep in mind that the expression is not part of the table _type_. Table types appear in other places as well, such as table imports. The expression only appears in table _definitions_. Technically, we could still encode a bit choosing its presence in the type, but that would be a somewhat odd factoring, since it would only be meaningful in some contexts.

(Also, I believe the specific bit you chose should be reserved for the `shared` attribute, as occupied in memory limits by the threads proposal – not yet available on tables but eventually will be.)

**Comment by manoskouk** [comment]
Good points.
If we want an optional initializer for nullable tables, we will have to encode this bit somewhere, and I don't see where else it could go. Another (probably better) solution would be to not allow custom initializers for nullable tables. 
In any case, we should reserve both the second ("shared") and third ("memory64") bits.

**Comment by rossberg** [comment]
> I don't see where else it could go

Well, see #65. ;)

> not allow custom initializers for nullable tables

That case might be useful, though. More importantly, parsing should not depend on semantics. We don't know how we'll want to extend the type system in the future, and whether a type is nullable might not always be syntactically apparent locally.
