### ISSUE TITLE
ref.is_null and heaptype vs. reftype

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/function-references#29]
The reference types proposal introduces `ref.null` and `ref.is_null` and defines them both to take a "reftype" immediate, which as of that proposal means either `extern` or `func`.

This proposal introduces a distinction between "reftype" and "heaptype", with the relation `reftype = (ref null? <heaptype>)`. The newly added reference-related instructions take "heaptype" immediates; `ref.null` and `ref.is_null` are not updated. This looks like an oversight to me; I think they should both be refined to take a "heaptype" immediate.

As far as the binary encoding is concerned, `-0x10` encodes either `func` (heaptype) or `funcref` (reftype) depending on context; `-0x11` does the same for "extern(ref)". So this spec change would not create backwards compatibility issues for binary modules.

Beyond consistency, the motivation is that now that the set of "reftypes" includes nullable and non-nullable types, it's a bit silly to use this definition for null-related instructions. For instance, while `ref.null <ref null $ht>` (with $ht being a heaptype) makes sense, `ref.null <ref $ht>` would be pointless (and would either have to fail validation, or trap, or return a value of type `(ref null $ht)`, contradicting its immediate).  

Similarly, `ref.is_null <ref $ht> : [(ref $ht) -> (i32.const 0)]` would be legal but useless: why would anyone want to do a null-check on a value that's statically known to be non-nullable?

For non-shorthands, a "reftype" is one byte bigger than a "heaptype", so given that the extra byte provides zero value, I suggest to switch `ref.null` and `ref.is_null` to "heaptypes" to save binary module size.

**Comment by rossberg** [comment]
Ah, yes, that's certainly the intention, and what's implemented in the interpreter as well. I updated the overview to mention this.

**Comment by jakobkummerow** [comment]
Fixed by #30. Thanks!
