### ISSUE TITLE
Heap type encoding

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/function-references#32]
Could the heap type encoding be changed to s32? It would make implementations slightly simpler, and it seems unlikely that a module would contain more than 2^31 type definitions.

**Comment by rossberg** [comment]
I think it's preferable to avoid incoherent range restrictions. And it follows the precedence of [blocktypes](https://webassembly.github.io/spec/core/binary/instructions.html#binary-blocktype), which also use s33.

**Comment by Horcrux7** [comment]
I was also wondering what the meaning behind this s33 is. It will be a nice test the WASM runtime to crash with a crazy number of types.

**Comment by binji** [comment]
We require an s33 for block types, but the [JS spec already limits it to 1'000'000](https://webassembly.github.io/spec/js-api/index.html#limits). I think we could do the same for heap types.

**Comment by rossberg** [comment]
@binji, good point, and nothing needs to be done there: this is a restriction on the type index space, so it immediately applies to heap types as well.
