### ISSUE TITLE
Interaction between 'let' and name section

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/function-references#37]
Are there any thoughts about how 'let' should interact with the name section? I see two issues:
- Since local indexes shift inside the scope of 'let', a consumer of the name section (e.g. debugger) has to track those scopes (or at least the number of bound locals).
-  There is no way to assign names to let-bound variables in the name section.

On a more general note, since 'let' seems to be creating some complications, maybe it should be removed and replaced with the rule that non-defaultable locals must be (trivially) provably initialized before use.

**Comment by rossberg** [comment]
Agreed, the name section should eventually support let.

> since 'let' seems to be creating some complications, maybe it should be removed and replaced with the rule that non-defaultable locals must be (trivially) provably initialized before use.

Yeah, but that would amount to control-flow-dependent type checking. Such systems tend to create considerably more complications, and a "trivial" approximation quickly becomes wishful thinking -- there always is another useful case that somebody wants to see handled.

**Comment by RossTate** [comment]
If label types are extended to be able to specify that certain locals must be defined, that addresses all those complications.

**Comment by rossberg** [comment]
Let was removed, so this is obsolete.
