### ISSUE TITLE
Time for a rendered spec :)

### ISSUE THREAD

**Issue by wingo** [WebAssembly/function-references#38]
Hey it would be swell if we got the HTML version rendered and posted :)  Would be happy to help out if needed!

**Comment by rossberg** [comment]
First we have to write it. :) But I plan to be doing that once reftypes has been merged into the main spec.

**Comment by Ms2ger** [comment]
> First we have to write it. :) But I plan to be doing that once reftypes has been merged into the main spec.

I believe this has happened now.

**Comment by dbezhetskov** [comment]
Well, formally there is no any reasons not to write the spec, reference types have been merged into the main spec and at least JSC team have added support for call.ref (https://bugs.webkit.org/show_bug.cgi?id=222903) and V8 team have done a lot of work in that area (https://bugs.chromium.org/p/v8/issues/detail?id=9495&q=typed%20function%20references&can=2). I think it is time to write the spec. @rossberg, you mentioned previously that you are going to do this, so I gently ping you on this

**Comment by rossberg** [comment]
Update: most of the spec has been there for a while, but still missing:

* Tracking initialization status of locals, as recently decided.
* Semantic representation of types (#51).
* Updating the proof appendix.
* Random todos.

**Comment by rossberg** [comment]
The spec is completed.
