### ISSUE TITLE
Heap types as table types?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/function-references#39]
Before this proposal, you can specify a table as having externref or funcref.  In the summary of this proposal, it includes the text:

> Add a new form of typed reference type ref $t and a nullable variant ref (null $t), where $t is a type index; can be used as both a value type or an element type for tables

However the spec does not appear to be updated to include this extension.  If the summary is still accurate, then this change is a TODO :)

**Comment by rossberg** [comment]
This was just a typo (or outdated syntax, I don't remember) in the overview, the latter should have been `(ref null $t)`. Just pushed a fix.

Other than that, these types can already be used as element types, since element types have already been redefined to be any ref type in the reftype proposal. Or am I missing something?

**Comment by wingo** [comment]
Well, https://github.com/WebAssembly/function-references/blob/master/document/core/syntax/types.rst#table-types says that a table's type is reftype.  But reftype is just externref or funcref, right? https://github.com/WebAssembly/function-references/blob/master/document/core/syntax/types.rst#reference-types

I could be reading this wrong; I have a hard time reading the raw rst :)

**Comment by rossberg** [comment]
Oh, you mean in the actual spec document? That has not been updated yet in this repo. ;)  So far, I've only done the overview (which should be fairly precise) and the reference interpreter. The relevant piece of the extension is described [here](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md#reference-types).

**Comment by wingo** [comment]
Ah :)  I had understood that the spec was updated; as you can see I was looking narrowly for a particular question :)  Perhaps we should update the root README.md to indicate that the spec is not updated yet.

**Comment by rossberg** [comment]
The spec doc has been updated.
