### ISSUE TITLE
Are inline heap types allowed in the text format?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/function-references#42]
Is this valid?

```webassembly
(module
  (func $foo (param (ref null (func (param i32)))))
)
```

Or would it have to be written like this:

```webasssembly
(module
  (type $takes_i32 (func (param i32)))
  (func $foo (param (ref null $takes_i32)))
)
```

The abstract syntax given in the overview defines heaptype as `heaptype ::= <typeidx> | func | extern`, which would imply that the first option is invalid, but I'm not sure if that's meant to apply to the concrete text format as well.

cc @kripken

**Comment by rossberg** [comment]
We could go either way. For now I'd have a slight preference not to introduce much extra sugar in the text format. If you use a concrete reference type, you'll probably have to write it in multiple places, in which case you want a name for it anyway. Do you think the sugar is worth it?

**Comment by tlively** [comment]
Thanks, @rossberg! FWIW, I share your slight preference :)
