### ISSUE TITLE
 Build depends on old OCaml version

### ISSUE THREAD

**Issue by titzer** [WebAssembly/function-references#43]
While the mainline spec repo has moved onto OCaml version 4.10, this repo still depends on an earlier version. This makes it hard to work on multiple proposals at once.

Can we rebase this repo on the current spec repo?

**Comment by rossberg** [comment]
Merged reference types repo, which should fix the problem. (I had hoped to be able to do the merge after reftypes have landed upstream, since it required resolving some tricky conflicts. Hope I don't have to redo all of them later.)

Let me know if there are still problems.

**Comment by titzer** [comment]
Thanks!
