### ISSUE TITLE
[docs] Typo in Overview.md ($x is referred to as $i).

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/function-references#47]
In [Overview.md][1] (*Typed Function References for WebAssembly*), the first code example has a typo in the `$inc` function. It takes a (single) param, named `$x`, but uses `local.get` on a param named `$i`.

``` wat
(type $i32-i32 (func (param i32) (result i32)))

(func $hof (param $f (ref $i32-i32)) (result i32)
  (i32.add (i32.const 10) (call_ref (i32.const 42) (local.get $f)))
)

(func $inc (param $x i32) (result i32)      ;; here it's $x
  (i32.add (local.get $i) (i32.const 1))    ;; here it's $i
)

(func $caller (result i32)
  (call $hof (ref.func $inc))
)
```

[1]: https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md

**Comment by rossberg** [comment]
Thanks, fixed.
