### ISSUE TITLE
Down casts from `funcref` to `ref t`

### ISSUE THREAD

**Issue by binji** [WebAssembly/function-references#5]
I don't see downcasts in this proposal, but they are listed as possible extensions here: https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#down-casts

Without these, I suppose the way you can call a `funcref` is by putting it in a table and using `call_indirect`? Seems like it would be nice to avoid this. Is it worth adding to this proposal?

**Comment by rossberg** [comment]
Down casts are the most complicated (and least resolved) part of the GC proposal, so they are intentionally left out here. That is, `funcref` can indeed only be called through tables -- I would hope that there isn't much reason to use `funcref` elsewhere anyway, at least not in the presence of `optref`. Do you have a specific use case in mind? (I saw the host binding thread, but for that optref would seem sufficient?)

**Comment by binji** [comment]
Yes, that was the case I was thinking of, and `optref` would be sufficient.

**Comment by rossberg** [comment]
This has been answered.
