### ISSUE TITLE
Remove `let`

### ISSUE THREAD

**Issue by titzer** [WebAssembly/function-references#57]
In #44, we discussed many alternatives to `let`. From the temperature of the discussion, it seems like an unstated consensus that we should remove `let` as it is.

I propose we do go ahead and remove `let` for now, in the spirit that we should not have incomplete features that we do not intend to ship laying around. We therefore better capture the subset that we do intend to ship.

That leaves us without a solution for non-nullable locals for now. I'm OK with that; it will expose pain points and increase the priority of finding a solution.

**Comment by tlively** [comment]
That sounds reasonable to me. We should also kick the discussion in #44 again to try to settle on a solution.

**Comment by rossberg** [comment]
Deprecating before there is a workable replacement is a strategy I'd prefer to avoid here. ;) That creates more churn and leaves some downstream code in limbo (e.g. my compilers).

Agreed that we should kick resolving this remaining issue. No fundamentally new ideas have come up since the last presentation, so I believe some variant of tracked locals still is our best option.

**Comment by titzer** [comment]
@rossberg This change is not churn. Rather, it's more like hill-climbing, as we incrementally move this proposal closer to what we will ship. Removing `let` narrows the set of uncertainties. Frankly, given that it's been over a year since the thread on `let` alternatives was started, we need to actually *do* something at this point.

Leaving some non-production code in limbo is a good kind of uncomfortable IMO; otherwise we are implicitly accepting dependencies that keep us at a standstill.

From my perspective, we should strive to keep proposals (and their test suites) as reflective of the current consensus as possible, and that sometimes means removing things that are unviable before the replacement is hashed out. Otherwise we are not even presenting a coherent target for new producers, but inviting confusion and more unwanted dependencies on features we know we are not going to ship, but haven't done any work to tackle.

**Comment by rossberg** [comment]
Let was removed.
