### ISSUE TITLE
Validating local.get in nested blocks with unreachable

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/function-references#74]
Should the following module validate?

```
(module
  (func
    (local (ref 0))
    unreachable
    block
      local.get 0
    end
  )
)
```

The declarative rule for `unreachable` indicates that it is valid for any instruction type, and therefore can `set` any local in the context, which would allow this module to validate.

The algorithm in the appendix however only checks the top control item for unreachable (`ctrls[0].unreachable`), which would cause this module to not validate, as there are no other `local.set` instructions in the module.

Put another way, is 'local.set polymorphism' inherited to nested blocks?

**Comment by conrad-watt** [comment]
IMO there are three possible solutions (@rossberg probably has opinions here)

1 - `unreachable` and similar should only be valid for instruction types with _empty_ init components (i.e. be conservative - no "`local.set` polymorphism" for now)

2 - "`local.set` polymorphism" should be inherited to nested blocks

3 (with apologies to the dead horse) - we introduce a stack bottom type, and the initialisation check for non-nullable locals is skipped if the input stack type is bottom (i.e. "`local.set` polymorphism" is _not_ inherited to nested blocks)

**Comment by eqrion** [comment]
(1) IIUC, would be the easiest to implement, as we just do nothing extra on unreachable/etc, and don't need to add another condition to `local.get`. local.get is the hottest instruction, so that's nice.

(2) will require us to maintain a new bit for 'parentOrSelfIsPolymorphic' on our control stack that we would check on every `local.get` to skip validation.

(3) seems similar to (2) but with the bit just local to the current control stack entry. (outside of the other impacts relaxed-dead-code would have)

From an implementers perspective, (1) seems the best. I don't know if there would be a forward compat concern with a future block annotation to allow initialization to persist out of a block though.

**Comment by rossberg** [comment]
Good catch! I agree that going with (1) makes most sense. The motivating examples for allowing stack polymorphism are much less concerned with init status, so we don't have to extend it to that. And it's the conservative choice.

Please see #75.

**Comment by conrad-watt** [comment]
> From an implementers perspective, (1) seems the best. I don't know if there would be a forward compat concern with a future block annotation to allow initialization to persist out of a block though.

For certain more ambitious across-block initialisation schemes, we'd need to reintroduce either (2) or (3), but that should be a forward compatible change as it would only allow more programs to validate.

**Comment by rossberg** [comment]
Closing via #75.
