### ISSUE TITLE
br_on_non_null.wast needs unreachable test

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/function-references#77]
It looks like a copy'n'paste typo. The file is missing unreachable test for br_on_non_null, but has one for the br_on_null.

https://github.com/WebAssembly/function-references/blob/959999dfbbfd737758637d3ccc734e1895095021/test/core/br_on_non_null.wast#L30

**Comment by rossberg** [comment]
Indeed. Fixed, thanks!
