### ISSUE TITLE
Runtime checks of call_ref

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/function-references#8]
In the overview it says:

> efficient indirect function calls without runtime checks

What does that mean in reality? What occur if count and types of values on the stack does not match with the calling function?

**Comment by rossberg** [comment]
That's a validation error.

**Comment by Horcrux7** [comment]
How can an validation error occur if there are no runtime checks?

**Comment by rossberg** [comment]
I'm afraid I don't understand the question. Validation happens before compilation and execution.

**Comment by Horcrux7** [comment]
How should validation occur before compilation? Can be that I does not have understand the concept.

My understand is:

- I can pass a variable of `func.ref` to any location.
- At runtime there can be in a `func.ref` variable a pointer to any function.
- The `call_ref` instruction hat no type information like `call_indrect`.
- At compile time, there is no knowledge of the number and type of function parameters.
- At compile time, there is no knowledge of the number and type of return values.

Of course, the Wasm file compiler has the necessary knowledge about the parameter types. But this not help the Wasm engine.

**Comment by rossberg** [comment]
Please see the Summary and following sections in the Overview doc. The central novelty in this proposal is the introduction of *typed* references `(ref $ty)`, which provide the validator with the necessary type information. The `func.ref` instruction creates such a typed function reference and the `call_ref` instruction can only be applied to such references (thus the name of the proposal).

**Comment by Horcrux7** [comment]
Ok, thank you. This important point I have oversee. Now all is clearer.
