### ISSUE TITLE
Extend `TableType` to support non-nullable references in JS-API

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/function-references#86]
Is JS API is missing the extension for `ElemType` at [Type Representation](https://github.com/WebAssembly/function-references/blob/main/proposals/function-references/Overview.md#type-representation) of the Overview? The [js-types](https://github.com/WebAssembly/js-types/blob/main/proposals/js-types/Overview.md#type-representation) defines:

```
type ElemType = "funcref"
type TableType = {limits: Limits, element: ElemType}
```

It looks like the ElemType will be simply `= "funcref" | {ref: ConsType, nullable: bool}`. Is this correct?

**Comment by rossberg** [comment]
Yeah, several pieces here are a bit outdated. I just created WebAssembly/js-types#40 to update the JS types overview for Wasm 2.0. That renames `ElemType` to `RefType` and adds `"externref"`.

I also updated the function ref overview to reflect our decision to go with the no-frills approach. That means we will not add the `{ref: ...}` form for the time being.
