### ISSUE TITLE
Progress toward phase 4

### ISSUE THREAD

**Issue by alexp-sssup** [WebAssembly/function-references#87]
I'd like to start a conversation around the state of this proposal and what steps are missing to bring it to Phase 4.

This is inspired by https://github.com/WebAssembly/tail-call/issues/15, which (seems to me) helped to focus the work of multiple actors towards making progress.

**Comment by tlively** [comment]
This is expected to advance to phase 4 at the same time as [GC](https://github.com/WebAssembly/gc). Most of the work is happening in the GC repo, so I would track progress over there. Everyone is also welcome to join the W3C community group [here](https://www.w3.org/community/webassembly/) then fill out [this form](https://forms.gle/JehrAB4gWbtHjybt9) to join the biweekly GC subgroup meetings.

**Comment by rossberg** [comment]
This has happened.
