### ISSUE TITLE
Default/init values in JS-API for globals and table.

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/function-references#94]
Currently, there is a test in SM codebase:

```
    let g = new WebAssembly.Global({value: "externref"});
    assertEq(g.value, null);
```

 With changes in how the `init` parameter works in the objects constructors (and `grow` method, and maybe `set` one), we are treating `externref` and `funcref` differently. The `DefaultValue`s for these two are different. If I read the JS-API spec correctly, the `externref` default value is `undefined`, and the `funcref` is `null`.

What is the right value for `g.value` with the current spec? Will the function-references proposal change the behavior?

**Comment by rossberg** [comment]
Inside Wasm, the default value for all (nullable) reference types is null, so I would expect the same here.

**Comment by yurydelendik** [comment]
https://webassembly.github.io/function-references/js-api/index.html#defaultvalue points to `ToWebAssemblyValue(undefined, valuetype)` for externref.  And https://webassembly.github.io/function-references/js-api/index.html#towebassemblyvalue does not really explain what undefined is mapped to.

**Comment by yurydelendik** [comment]
Moving discussion about `externref` to https://github.com/WebAssembly/spec/issues/1620
