### ISSUE TITLE
Clarification request: initializers for tables with non-nullable type and initial_size == 0

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/function-references#96]
A question that came up is whether initializers are required for tables that have a non-nullable type (which, generally, causes them to require an initializer) but initial_size zero (which makes any initializer useless).

My reading of the current text of https://github.com/WebAssembly/function-references/blob/main/proposals/function-references/Overview.md#tables is that initializers are required regardless of initial_size when the type is non-nullable. Is that interpretation correct? If yes, do we want to keep this rule, or allow the special case of skipping the initializer when the initial_size is 0?

(Personally, I don't feel strongly about this either way; just asking to clarify.)

**Comment by rossberg** [comment]
Yes, the spec requires it. I think we should avoid making special cases, unless there is a really strong reason.

I just created #97 to add a few tests. PTAL.

**Comment by wingo** [comment]
@rossberg I think this effectively prohibits having a table with non-nullable type, if you don't have a constant expression initializer for that type.  Consider (with GC):

```
(type $s (struct (ref extern))
(table 0 (ref $s) ???)
```

Is there something you can put in the `???` ?  You probably don't have a non-null `(ref extern)` at init-time.

**Comment by rossberg** [comment]
I'm not actually sure if non-nullable extern refs are ever a useful type. But it's easy to fabricate one:
```
(extern.externalize (i31.new (i32.const 0)))
```
I suppose the bigger annoyance in your example is that you have to fabricate a struct as well. I take your point that this is a bit redundant in cases where you start with an empty table. But I'd like to see if this actually is a relevant pain point in practice before introducing special cases. Not allowing it for now is conservative.
